In [11]:
import sqlite3

conn = sqlite3.connect('orgdb.sqlite')
cur = conn.cursor()

cur.execute('DROP TABLE IF EXISTS Counts')

cur.execute('''
CREATE TABLE Counts (org TEXT, count INTEGER)''')

fname = input('Enter file name: ')
if (len(fname) < 1): fname = 'src/mbox-short.txt'
fh = open(fname)
for line in fh:
    if not line.startswith('From '): continue
    email = line.split()[1]
    org = email.split('@')[1]
    cur.execute('SELECT count FROM Counts WHERE org = ? ', (org,))
    row = cur.fetchone()
    if row is None:
        cur.execute('''INSERT INTO Counts (org, count)
                VALUES (?, 1)''', (org,))
    else:
        cur.execute('UPDATE Counts SET count = count + 1 WHERE org = ?',
                    (org,))
    conn.commit()

# https://www.sqlite.org/lang_select.html
sqlstr = 'SELECT org, count FROM Counts ORDER BY count DESC LIMIT 10'

for row in cur.execute(sqlstr):
    print(str(row[0]), row[1])

cur.close()

iupui.edu 536
umich.edu 491
indiana.edu 178
caret.cam.ac.uk 157
vt.edu 110
uct.ac.za 96
media.berkeley.edu 56
ufp.pt 28
gmail.com 25
et.gatech.edu 17

In [14]:
import xml.etree.ElementTree as ET
import sqlite3

conn = sqlite3.connect('trackdb.sqlite')
cur = conn.cursor()

# Make some fresh tables using executescript()
cur.executescript('''
DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS Album;
DROP TABLE IF EXISTS Track;
DROP TABLE IF EXISTS Genre;

CREATE TABLE Artist (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name    TEXT UNIQUE
);

CREATE TABLE Genre (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name    TEXT UNIQUE
);

CREATE TABLE Album (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    artist_id  INTEGER,
    title   TEXT UNIQUE
);

CREATE TABLE Track (
    id  INTEGER NOT NULL PRIMARY KEY 
        AUTOINCREMENT UNIQUE,
    title TEXT  UNIQUE,
    album_id  INTEGER,
    genre_id  INTEGER,
    len INTEGER, rating INTEGER, count INTEGER
);
''')


fname = input('Enter file name: ')
if ( len(fname) < 1 ) : fname = 'src/tracks/Library.xml'

# <key>Track ID</key><integer>369</integer>
# <key>Name</key><string>Another One Bites The Dust</string>
# <key>Artist</key><string>Queen</string>
def lookup(d, key):
    found = False
    for child in d:
        if found : return child.text
        if child.tag == 'key' and child.text == key :
            found = True
    return None

stuff = ET.parse(fname)
all = stuff.findall('dict/dict/dict')
print('Dict count:', len(all))
for entry in all:
    if ( lookup(entry, 'Track ID') is None ) : continue

    name = lookup(entry, 'Name')
    artist = lookup(entry, 'Artist')
    album = lookup(entry, 'Album')
    count = lookup(entry, 'Play Count')
    rating = lookup(entry, 'Rating')
    length = lookup(entry, 'Total Time')
    genre = lookup(entry, 'Genre')

    if name is None or artist is None or album is None or genre_id is None: 
        continue

    print(name, artist, album, count, rating, length, genre)

    cur.execute('''INSERT OR IGNORE INTO Artist (name) 
        VALUES ( ? )''', ( artist, ) )
    cur.execute('SELECT id FROM Artist WHERE name = ? ', (artist, ))
    artist_id = cur.fetchone()[0]

    cur.execute('''INSERT OR IGNORE INTO Album (title, artist_id) 
        VALUES ( ?, ? )''', ( album, artist_id ) )
    cur.execute('SELECT id FROM Album WHERE title = ? ', (album, ))
    album_id = cur.fetchone()[0]

    
    cur.execute('''INSERT OR IGNORE INTO Genre (name) 
        VALUES ( ? )''', ( genre, ) )
    cur.execute('SELECT id FROM Genre WHERE name = ? ', (genre, ))
    genre_id = cur.fetchone()[0]

    cur.execute('''INSERT OR REPLACE INTO Track
        (title, album_id, genre_id, len, rating, count) 
        VALUES ( ?, ?, ?, ?, ?, ? )''', 
        ( name, album_id, genre_id, length, rating, count ) )

    conn.commit()

Dict count: 404
Another One Bites The Dust Queen Greatest Hits 55 100 217103 Rock
Asche Zu Asche Rammstein Herzeleid 79 100 231810 Industrial
Beauty School Dropout Various Grease 48 100 239960 Soundtrack
Black Dog Led Zeppelin IV 109 100 296620 Rock
Bring The Boys Back Home Pink Floyd The Wall [Disc 2] 33 100 87118 Rock
Circles Bryan Lee Blues Is 54 60 355369 Funk
Comfortably Numb Pink Floyd The Wall [Disc 2] 36 100 384130 Rock
Crazy Little Thing Called Love Queen Greatest Hits 38 100 163631 Rock
Electric Funeral Black Sabbath Paranoid 44 100 293015 Metal
Fat Bottomed Girls Queen Greatest Hits 38 100 257515 Rock
For Those About To Rock (We Salute You) AC/DC Who Made Who 84 100 353750 Rock
Four Sticks Led Zeppelin IV 84 100 284421 Rock
Furious Angels Rob Dougan The Matrix Reloaded 54 100 330004 Soundtrack
Gelle Bryan Lee Blues Is 45 60 199836 Blues/R&B
Going To California Led Zeppelin IV 100 100 215666 Rock
Grease Various Grease 42 100 205792 Soundtrack
Hand of Doom Black Sabbath Paranoid 36 100 429609 Metal
Hells Bells AC/DC Who Made Who 82 100 312946 Rock
Hey You Pink Floyd The Wall [Disc 2] 23 100 282305 Rock
I Worry Bryan Lee Blues Is 33 100 341315 Blues/R&B
Iron Man Black Sabbath Paranoid 39 100 358530 Metal
Is There Anybody Out There? Pink Floyd The Wall [Disc 2] 26 100 160679 Rock
It was a Very Good Year Frank Sinatra Greatest Hits 39 100 268852 Easy Listening
Its Your Move Bryan Lee Blues Is 40 100 245002 Blues/R&B
Jack the Stripper/Fairies Wear Boots Black Sabbath Paranoid 35 100 373995 Metal
Killer Queen Queen Greatest Hits 34 100 181368 Rock
Laichzeit Rammstein Herzeleid 41 100 262844 Industrial
Let me Down Easy Bryan Lee Blues Is 43 100 331441 Blues/R&B
Misty Mountain Hop Led Zeppelin IV 88 100 278831 Rock
No Low Down Bryan Lee Blues Is 39 100 245760 Blues/R&B
Now You Are Gone America Greatest Hits 52 100 187559 Easy Listening
Outside The Wall Pink Floyd The Wall [Disc 2] 16 100 104437 Rock
Paranoid Black Sabbath Paranoid 36 100 172930 Metal
Planet Caravan Black Sabbath Paranoid 38 100 274938 Metal
Pretty Jeanie Bryan Lee Blues Is 34 100 225175 Blues/R&B
Rammstein Rammstein Herzeleid 45 100 265090 Industrial
Rat Salad Black Sabbath Paranoid 46 100 150230 Metal
Rock & Roll Led Zeppelin IV 109 100 220891 Rock
Rode Across the Desert America Greatest Hits 60 100 249887 Easy Listening
Sandy Various Grease 36 100 155742 Soundtrack
Shake Your Foundations AC/DC Who Made Who 85 100 233769 Rock
Sister Golden Hair America Greatest Hits 60 100 202057 Easy Listening
Somebody To Love Queen Greatest Hits 17 100 297586 Rock
Stairway To Heaven Led Zeppelin IV 93 100 481567 Rock
Strangers in the Night Frank Sinatra Greatest Hits 42 100 158484 Easy Listening
Summer Nights Various Grease 35 100 216973 Soundtrack
Summer Wind Frank Sinatra Greatest Hits 46 100 177554 Easy Listening
Thats Life Frank Sinatra Greatest Hits 43 100 189988 Easy Listening
The Battle Of Evermore Led Zeppelin IV 110 100 351529 Rock
The Blues "Is" Bryan Lee Blues Is 45 100 252238 Blues/R&B
There it Is Bryan Lee Blues Is 35 100 395441 Blues/R&B
Think Bryan Lee Blues Is 41 100 320339 Blues/R&B
This Town Frank Sinatra Greatest Hits 44 100 185051 Easy Listening
Tin Man America Greatest Hits 50 100 210076 Easy Listening
Track 01 Billy Price Danger Zone 47 100 261825 Blues/R&B
Track 02 Billy Price Danger Zone 42 100 165459 Blues/R&B
Track 03 Billy Price Danger Zone 41 100 206471 Blues/R&B
Messin with the Kid The Canettes Blues Band Self Titled 23 100 226377 Blues/R&B
Track 04 Billy Price Danger Zone 37 100 257175 Blues/R&B
Stormy Monday The Canettes Blues Band Self Titled 29 100 464143 Blues/R&B
Track 05 Billy Price Danger Zone 42 100 230295 Blues/R&B
Waiting on Ice Bryan Lee Blues Is 37 100 289384 Blues/R&B
War Pigs/Luke's Wall Black Sabbath Paranoid 38 100 478197 Metal
We Are The Champions Queen Greatest Hits 24 100 181864 Rock
We Will Rock You Queen Greatest Hits 33 100 123559 Rock
When Somebody Loves You Frank Sinatra Greatest Hits 43 100 117263 Easy Listening
When The Levee Breaks Led Zeppelin IV 83 100 427624 Rock
You are the One that I Want Various Grease 31 100 169900 Soundtrack
You Done Me Wrong Bryan Lee Blues Is 35 100 200097 Blues/R&B
You Shook Me All Night Long AC/DC Who Made Who 92 100 210938 Rock
You're My Best Friend Queen Greatest Hits 31 100 172643 Rock
Zion Fluke The Matrix Reloaded 47 100 273528 Soundtrack
Who Made Who AC/DC Who Made Who 110 100 207203 Rock
D.T. AC/DC Who Made Who 90 None 173714 Rock
Sink the Pink AC/DC Who Made Who 83 None 253466 Rock
Ride On AC/DC Who Made Who 75 None 351268 Rock
Chase the Ace AC/DC Who Made Who 93 None 181420 Rock
Wollt Ihr Das Bett In Flammen Sehen Rammstein Herzeleid 50 None 317387 Industrial
Der Meister Rammstein Herzeleid 46 None 250801 Industrial
Weisses Fleisch Rammstein Herzeleid 52 None 215902 Industrial
Seemann Rammstein Herzeleid 34 None 288235 Industrial
Du Riechst So Gut Rammstein Herzeleid 50 None 289332 Industrial
Das Alte Leid Rammstein Herzeleid 46 None 344581 Industrial
Heirate Mich Rammstein Herzeleid 39 None 284734 Industrial
Herzeleid Rammstein Herzeleid 42 None 223425 Industrial
Baba O'Riley The Who Who's Next 45 None 298448 Rock
Bargain The Who Who's Next 37 None 331676 Rock
Love Ain't for Keeping The Who Who's Next 24 None 130560 Rock
My Wife The Who Who's Next 17 None 213786 Rock
The Song Is Over The Who Who's Next 14 None 375797 Rock
Getting In Tune The Who Who's Next 27 None 288809 Rock
Going Mobile The Who Who's Next 28 100 221910 Rock
Behind Blue Eyes The Who Who's Next 43 None 221570 Rock
Won't Get Fooled Again The Who Who's Next 21 None 511111 Rock
Folsom Prison Blues Johnny Cash The Legend Of Johnny Cash 47 100 170004 Country
I Walk The Line Johnny Cash The Legend Of Johnny Cash 33 100 165720 Country
Get Rhythm Johnny Cash The Legend Of Johnny Cash 35 100 134530 Country
Big River Johnny Cash The Legend Of Johnny Cash 51 None 152711 Country
Guess Things Happen That Way Johnny Cash The Legend Of Johnny Cash 35 None 111386 Country
Ring Of Fire Johnny Cash The Legend Of Johnny Cash 30 100 157100 Country
Jackson Johnny Cash The Legend Of Johnny Cash 35 100 166530 Country
A Boy Named Sue (live) Johnny Cash The Legend Of Johnny Cash 37 None 226063 Country
You Raise Me Up Selah Hiding Place 9 None 302262 Gospel & Religious
Hold On, I'm Coming The Canettes Blues Band On Tap & In the Can 34 100 282566 Blues/R&B
Got my Mojo Working The Canettes Blues Band On Tap & In the Can 52 100 310517 Blues/R&B
Sweet Home Chicago The Canettes Blues Band On Tap & In the Can 27 100 375849 Blues/R&B
Heavy Love The Canettes Blues Band On Tap & In the Can 28 100 253544 Blues/R&B
Cold Cold Feeling The Canettes Blues Band On Tap & In the Can 43 100 261929 Blues/R&B
Lonely Avenue The Canettes Blues Band On Tap & In the Can 24 100 292022 Blues/R&B
Good Morning Little Schoolgirl The Canettes Blues Band On Tap & In the Can 20 100 278648 Blues/R&B
Dust My Broom The Canettes Blues Band On Tap & In the Can 24 100 299311 Blues/R&B
Gimme' Some Lovin The Canettes Blues Band On Tap & In the Can 35 100 227239 Blues/R&B
Everybody Needs Somebody to Love The Canettes Blues Band On Tap & In the Can 24 100 195186 Blues/R&B
Black Magic Woman The Canettes Blues Band On Tap & In the Can 31 100 442644 Blues/R&B
Steppin' Rooster The Canettes Blues Band On Tap & In the Can 21 100 704862 Blues/R&B
Our Love is Drifting The Canettes Blues Band On Tap & In the Can 15 100 292649 Blues/R&B
Doin' 100 The Canettes Blues Band On Tap & In the Can 20 100 343980 Blues/R&B
Mother Joy Matt Ender Natural Wonders Music Sampler 1999 463 None 287294 New Age
Soldier's Lament Steve McDonald Natural Wonders Music Sampler 1999 371 None 347193 New Age
Dulaman Altan Natural Wonders Music Sampler 1999 403 None 223007 New Age
The Arrow Chris Spheeris Natural Wonders Music Sampler 1999 416 None 319869 New Age
Spanish Eyes La Esperanza Natural Wonders Music Sampler 1999 375 None 259030 New Age
Banana Bay Luis Villegas Natural Wonders Music Sampler 1999 403 None 198060 New Age
Aguas De Marco Rosa Passos Natural Wonders Music Sampler 1999 407 None 179408 New Age
Tamborea Energipsy Natural Wonders Music Sampler 1999 355 None 235389 New Age
Gone Hollie Smith Natural Wonders Music Sampler 1999 362 None 196414 New Age
The Immigrant Joanie Madden Natural Wonders Music Sampler 1999 350 None 362631 New Age
Pahrump-Big Water Cusco Natural Wonders Music Sampler 1999 342 None 191634 New Age
Seeker's Quest Cheryl Gunn Natural Wonders Music Sampler 1999 337 None 236434 New Age
Floating To Forever Dean Everson Natural Wonders Music Sampler 1999 337 None 351686 New Age
Open Road Jeff Bailey Relaxing Jazz 10 None 318563 Jazz
Ruby Kaiser Chiefs Yours Truly, Angry Mob 13 None 205008 Alternative & Punk
The Angry Mob Kaiser Chiefs Yours Truly, Angry Mob 41 None 288313 Alternative & Punk
Heat Dies Down Kaiser Chiefs Yours Truly, Angry Mob 12 None 237061 Alternative & Punk
Highroyds Kaiser Chiefs Yours Truly, Angry Mob 10 None 199575 Alternative & Punk
Love's Not A Competition (But I'm Winning) Kaiser Chiefs Yours Truly, Angry Mob 11 None 197799 Alternative & Punk
Thank You Very Much Kaiser Chiefs Yours Truly, Angry Mob 11 None 157753 Alternative & Punk
I Can Do It Without You Kaiser Chiefs Yours Truly, Angry Mob 11 None 204199 Alternative & Punk
My Kind Of Guy Kaiser Chiefs Yours Truly, Angry Mob 10 None 246595 Alternative & Punk
Everything Is Average Nowadays Kaiser Chiefs Yours Truly, Angry Mob 16 None 164754 Alternative & Punk
Learnt My Lesson Well Kaiser Chiefs Yours Truly, Angry Mob 9 None 325955 Alternative & Punk
Try Your Best Kaiser Chiefs Yours Truly, Angry Mob 8 None 222511 Alternative & Punk
Retirement Kaiser Chiefs Yours Truly, Angry Mob 10 None 237426 Alternative & Punk
The Angry Mob [Live From Berlin] Kaiser Chiefs Yours Truly, Angry Mob 40 None 279066 Alternative & Punk
I Like To Fight Kaiser Chiefs Yours Truly, Angry Mob 8 None 218566 Alternative & Punk
From The Neck Down Kaiser Chiefs Yours Truly, Angry Mob 15 None 147226 Alternative & Punk
Bomb Squad (TECH) Brent Brent's Album 4 None 208065 None

TypeError: 'NoneType' object is not subscriptable

In [23]:
import json
import sqlite3

conn = sqlite3.connect('rosterdb.sqlite')
cur = conn.cursor()

# Do some setup
cur.executescript('''
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Member;
DROP TABLE IF EXISTS Course;

CREATE TABLE User (
    id     INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name   TEXT UNIQUE
);

CREATE TABLE Course (
    id     INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    title  TEXT UNIQUE
);

CREATE TABLE Member (
    user_id     INTEGER,
    course_id   INTEGER,
    role        INTEGER,
    PRIMARY KEY (user_id, course_id)
)
''')

fname = input('Enter file name: ')
if len(fname) < 1:
    fname = 'roster_data.json'

# [
#   [ "Charley", "si110", 1 ],
#   [ "Mea", "si110", 0 ],

str_data = open(fname).read()
json_data = json.loads(str_data)

for entry in json_data:

    name = entry[0]
    title = entry[1]
    role = entry[2]

    print((name, title, role))

    cur.execute('''INSERT OR IGNORE INTO User (name)
        VALUES ( ? )''', ( name, ) )
    cur.execute('SELECT id FROM User WHERE name = ? ', (name, ))
    user_id = cur.fetchone()[0]

    cur.execute('''INSERT OR IGNORE INTO Course (title)
        VALUES ( ? )''', ( title, ) )
    cur.execute('SELECT id FROM Course WHERE title = ? ', (title, ))
    course_id = cur.fetchone()[0]

    cur.execute('''INSERT OR REPLACE INTO Member
        (user_id, course_id, role) VALUES ( ?, ?, ? )''',
        ( user_id, course_id, role ) )
    
    cur.execute('SELECT role FROM Member WHERE user_id = ? AND course_id = ?', (user_id, course_id))
    role = cur.fetchone()[0]

    conn.commit()

('Riva', 'si110', 1)
('Rikki', 'si110', 0)
('Chenille', 'si110', 0)
('Bilal', 'si110', 0)
('Codey', 'si110', 0)
('Nick', 'si110', 0)
('Amos', 'si110', 0)
('Rheyden', 'si110', 0)
('Blessing', 'si110', 0)
('Avya', 'si110', 0)
('Jole', 'si110', 0)
('Esme', 'si110', 0)
('Emmanuel', 'si110', 0)
('Mohaddesa', 'si110', 0)
('Ketsia', 'si110', 0)
('Lillie', 'si110', 0)
('Sethu', 'si110', 0)
('LLeyton', 'si110', 0)
('Morvyn', 'si110', 0)
('Havin', 'si110', 0)
('Lia', 'si110', 0)
('Connar', 'si110', 0)
('Kiran', 'si110', 0)
('Kayleigh', 'si110', 0)
('Nikash', 'si110', 0)
('Lance', 'si110', 0)
('Kenan', 'si110', 0)
('Sanaa', 'si110', 0)
('Archibald', 'si110', 0)
('Cailyn', 'si110', 0)
('Kennedy', 'si110', 0)
('Bronagh', 'si110', 0)
('Zen', 'si110', 0)
('Benjamin', 'si110', 0)
('Ennis', 'si106', 1)
('Raul', 'si106', 0)
('Rasul', 'si106', 0)
('Name', 'si106', 0)
('Xanthe', 'si106', 0)
('Vasemaca', 'si106', 0)
('Cathal', 'si106', 0)
('Fern', 'si106', 0)
('Daniyal', 'si106', 0)
('Abid', 'si106', 0)
('Alx', 'si106', 0)
('Kaylea', 'si106', 0)
('Hind', 'si106', 0)
('Kienan', 'si106', 0)
('Marvellous', 'si106', 0)
('Fabian', 'si106', 0)
('Surya', 'si106', 0)
('Brenae', 'si106', 0)
('Kori', 'si106', 0)
('Hailie', 'si106', 0)
('Rebekkah', 'si106', 0)
('Blaike', 'si106', 0)
('Demileigh', 'si106', 0)
('Kizzy', 'si106', 0)
('Ilyaas', 'si106', 0)
('Deni', 'si106', 0)
('Coralie', 'si106', 0)
('Kareena', 'si106', 0)
('Muqadaas', 'si106', 0)
('Sohaa', 'si206', 1)
('Romi', 'si206', 0)
('Bob', 'si206', 0)
('Maree', 'si206', 0)
('Tobie', 'si206', 0)
('Alaska', 'si206', 0)
('Fendi', 'si206', 0)
('Taliesin', 'si206', 0)
('Koddi', 'si206', 0)
('Gideon', 'si206', 0)
('Andreas', 'si206', 0)
('Ciara', 'si206', 0)
('Clarke', 'si206', 0)
('Kelisse', 'si206', 0)
('Macaully', 'si206', 0)
('Isaac', 'si206', 0)
('Ferre', 'si206', 0)
('Sonniva', 'si206', 0)
('Caine', 'si206', 0)
('Tye', 'si206', 0)
('Aphra', 'si206', 0)
('Rui', 'si206', 0)
('Katarzyna', 'si206', 0)
('Skye', 'si206', 0)
('Kathryn', 'si206', 0)
('Myles', 'si206', 0)
('Teresa', 'si206', 0)
('Ashley', 'si206', 0)
('Jad', 'si206', 0)
('Arthur', 'si206', 0)
('Kensey', 'si206', 0)
('Kalena', 'si206', 0)
('Leroy', 'si206', 0)
('Ameer', 'si206', 0)
('Miyha', 'si206', 0)
('Sofia', 'si206', 0)
('Kia', 'si206', 0)
('Amara', 'si206', 0)
('Tyrnan', 'si206', 0)
('Ruaidhri', 'si206', 0)
('Denon', 'si206', 0)
('Jaime', 'si206', 0)
('Russel', 'si301', 1)
('Spondon', 'si301', 0)
('Momina', 'si301', 0)
('Matej', 'si301', 0)
('Zarran', 'si301', 0)
('Konan', 'si301', 0)
('Daphne', 'si301', 0)
('Harper', 'si301', 0)
('Aleksandrs', 'si301', 0)
('Tammam', 'si301', 0)
('Stefin', 'si301', 0)
('Harper', 'si301', 0)
('Kodey', 'si301', 0)
('Kenyon', 'si301', 0)
('Stuart', 'si301', 0)
('Eubh', 'si301', 0)
('Lyndsay', 'si301', 0)
('Paula', 'si301', 0)
('Rayaan', 'si301', 0)
('Uzayr', 'si301', 0)
('Kaelyn', 'si301', 0)
('Marwad', 'si301', 0)
('Arsalan', 'si301', 0)
('Ebony', 'si301', 0)
('Nicki', 'si301', 0)
('Arran', 'si301', 0)
('Caie', 'si301', 0)
('Neela', 'si301', 0)
('Ally', 'si301', 0)
('Tomasz', 'si301', 0)
('Rumaysa', 'si301', 0)
('Fabian', 'si301', 0)
('Gustav', 'si301', 0)
('Nafeesa', 'si301', 0)
('Reilly', 'si301', 0)
('Josiah', 'si301', 0)
('Dermot', 'si310', 1)
('Riach', 'si310', 0)
('Jason', 'si310', 0)
('Rheo', 'si310', 0)
('Harjeevan', 'si310', 0)
('Tabbitha', 'si310', 0)
('Kirstie', 'si310', 0)
('Suzy', 'si310', 0)
('Merab', 'si310', 0)
('Rory', 'si310', 0)
('Avanya', 'si310', 0)
('Faizaan', 'si310', 0)
('Clara', 'si310', 0)
('Bobbie', 'si310', 0)
('Spondon', 'si310', 0)
('Lena', 'si310', 0)
('Sonni', 'si310', 0)
('Maizy', 'si310', 0)
('Lennen', 'si310', 0)
('Shantelle', 'si310', 0)
('Demileigh', 'si310', 0)
('Ciarian', 'si310', 0)
('Catherine', 'si310', 0)
('Nidhish', 'si310', 0)
('Elias', 'si310', 0)
('Zainib', 'si310', 0)
('Amirah', 'si334', 1)
('Rehan', 'si334', 0)
('Jack', 'si334', 0)
('Setana', 'si334', 0)
('Tokunbo', 'si334', 0)
('Kerriannah', 'si334', 0)
('Arissa', 'si334', 0)
('Qasim', 'si334', 0)
('Hong', 'si334', 0)
('Iestyn', 'si334', 0)
('Bo', 'si334', 0)
('Farhan', 'si334', 0)
('Eliana', 'si334', 0)
('Serene', 'si334', 0)
('Elice', 'si334', 0)
('Vinay', 'si334', 0)
('Amylea', 'si334', 0)
('Cator', 'si334', 0)
('Rishi', 'si334', 0)
('Miku', 'si334', 0)
('Greer', 'si334', 0)
('Benjamin', 'si334', 0)
('Zainab', 'si334', 0)
('Kenton', 'si334', 0)
('Jak', 'si334', 0)
('Bronte', 'si334', 0)
('Celsea', 'si334', 0)
('Roxanne', 'si334', 0)
('Taiwo', 'si334', 0)
('Ashleigh', 'si334', 0)
('Daigan', 'si334', 0)
('Anja', 'si334', 0)
('Desmond', 'si334', 0)
('Unaiza', 'si334', 0)
('Zacharie', 'si334', 0)
('Brendon', 'si334', 0)
('Meredith', 'si334', 0)
('Annoushka', 'si334', 0)
('Momina', 'si363', 1)
('Hunter', 'si363', 0)
('Kellen', 'si363', 0)
('Lawlyn', 'si363', 0)
('Aaraa', 'si363', 0)
('Bobby', 'si363', 0)
('Korey', 'si363', 0)
('Rhona', 'si363', 0)
('Lena', 'si363', 0)
('Devrin', 'si363', 0)
('Banan', 'si363', 0)
('Carisen', 'si363', 0)
('Genevieve', 'si363', 0)
('Iagan', 'si363', 0)
('Obieluem', 'si363', 0)
('Haseeb', 'si363', 0)
('Narvic', 'si363', 0)
('Harlie', 'si363', 0)
('Rhianne', 'si363', 0)
('Takua', 'si363', 0)
('Mirran', 'si363', 0)
('Otilija', 'si363', 0)
('Japjeet', 'si363', 0)
('Dylan', 'si363', 0)
('Mia', 'si363', 0)
('Fergie', 'si363', 0)
('Pamindar', 'si363', 0)
('Nyah', 'si363', 0)
('Benoit', 'si363', 0)
('Kayliegh', 'si363', 0)
('Ijay', 'si363', 0)
('Manahil', 'si363', 0)
('Mohammad', 'si363', 0)
('Sophi', 'si363', 0)
('Rana', 'si364', 1)
('Jock', 'si364', 0)
('Abu', 'si364', 0)
('Anja', 'si364', 0)
('Saif', 'si364', 0)
('Felicity', 'si364', 0)
('Safia', 'si364', 0)
('Faith', 'si364', 0)
('Oliver', 'si364', 0)
('Grzegorz', 'si364', 0)
('Geoff', 'si364', 0)
('Maura', 'si364', 0)
('Tiana', 'si364', 0)
('Naeema', 'si364', 0)
('Marcos', 'si364', 0)
('Nichole', 'si364', 0)
('Arann', 'si364', 0)
('Vicky', 'si364', 0)
('Rorie', 'si364', 0)
('Sher', 'si364', 0)
('Eleonora', 'si364', 0)
('Ambanimoh', 'si364', 0)
('Ice', 'si364', 0)
('Elisha', 'si364', 0)
('Michaela', 'si364', 0)
('Daria', 'si364', 0)
('Modu', 'si364', 0)
('Laci', 'si364', 0)
('Leanne', 'si364', 0)
('AJ', 'si364', 0)
('Alexandra', 'si364', 0)
('Rayne', 'si364', 0)
('Sophiann', 'si364', 0)
('Keeyra', 'si364', 0)
('Alfee', 'si364', 0)
('Nick', 'si364', 0)
('Kai', 'si364', 0)
('Brynmor', 'si364', 0)
('Koddi', 'si364', 0)
('Davina', 'si364', 0)
('Leighton', 'si364', 0)
('Uxia', 'si364', 0)
('Rhyse', 'si364', 0)
('Ramone', 'si364', 0)
('Slsbil', 'si364', 0)
('Adalaide', 'si364', 0)
('Kadie', 'si364', 0)
('Sami', 'si364', 0)
('Isobella', 'si364', 0)
('Bevin', 'si364', 0)
('Jesse', 'si422', 1)
('Pyper', 'si422', 0)
('Kaska', 'si422', 0)
('Wen', 'si422', 0)
('Tania', 'si422', 0)
('Broghan', 'si422', 0)
('Ffion', 'si422', 0)
('Abdallah', 'si422', 0)
('Mawahib', 'si422', 0)
('Wesley', 'si422', 0)
('Al', 'si422', 0)
('Larissa', 'si422', 0)
('Oluwademilade', 'si422', 0)
('Conli', 'si422', 0)
('Kia', 'si422', 0)
('Aleena', 'si422', 0)
('Stefany', 'si422', 0)
('Melice', 'si422', 0)
('Saumya', 'si422', 0)
('Elyse', 'si422', 0)
('Elidh', 'si430', 1)
('Seerat', 'si430', 0)
('Maryse', 'si430', 0)
('Henry', 'si430', 0)
('Conley', 'si430', 0)
('Lilygrace', 'si430', 0)
('Josef', 'si430', 0)
('Paolo', 'si430', 0)
('Aileigh', 'si430', 0)
('Puja', 'si430', 0)
('Briana', 'si430', 0)
('Rahel', 'si430', 0)
('Jack', 'si430', 0)
('Thia', 'si430', 0)
('Darrie', 'si430', 0)
('Rebekah', 'si430', 0)
('Karys', 'si430', 0)
('Caley', 'si430', 0)
('Meriem', 'si430', 0)
('Dyllan', 'si430', 0)
('Kuzivakwashe', 'si430', 0)
('Ashleen', 'si430', 0)
('Tammara', 'si430', 0)
('Lyndsay', 'si430', 0)
('Jaise', 'si430', 0)
('Daniyal', 'si430', 0)
('Shalamar', 'si430', 0)
('Bobbi', 'si430', 0)
('Jayse', 'si430', 0)
('Rikki', 'si430', 0)
('Brett', 'si430', 0)
('Quinn', 'si430', 0)
('Josi', 'si430', 0)
('Kyler', 'si430', 0)
('May', 'si430', 0)
('Katey', 'si430', 0)
('Tay', 'si430', 0)
('Honor', 'si430', 0)
('Kerri', 'si430', 0)
('Dior', 'si430', 0)
('Nash', 'si430', 0)
('Keith', 'si430', 0)
('Lilah', 'si430', 0)
('Maighdlin', 'si430', 0)
('Tanika', 'si430', 0)
('Hector', 'si430', 0)
('Maja', 'si430', 0)